@startuml
skinparam packageStyle rectangle
left to right direction

:User:
:Student:
:System:
:Database:

package "App" {
User --> (Login)
User --> (Signup)
(Signup) ..> (Create Username): <<include>>
(Signup) ..> (Create Password): <<include>>

(Re-enter Username) ..> (Create Username): <<extend>>[Username Invalid]
(Re-enter Password) ..> (Create Password): <<extend>>[Password Invalid]

(Re-enter Username) ..> (Login): <<extend>>[Username Invalid]
(Re-enter Password) ..> (Login): <<extend>>[Password Invalid]

(Account Created) ..> (Signup):<<extend>>[User and Pass Valid]
(Account Created) --> Database 
note left of (Account Created):"User becomes Student"



Student --> (View Previously Completed Courses)
Student --> (View GPA)
Student --> (Update Letter Grade)
Student --> (Delete Course)


System --> (Display all Previous Courses)
System --> (Calculate GPA)
System --> (Display GPA)


}

@enduml
